title: 寝ル猫 -Neruneko-
description: >
  寝ル猫が制作するインディーゲームの公式ポータルサイトです。
  This is the official portal for indie games created by Neruneko.
theme: jekyll-theme-cayman
markdown: kramdown
# Google Fontsの読み込みをNoto Sans JPに変更
include:
  - https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap